site_name: 趣味の数学・物理学・コンピュータサイエンス
site_url: https://rewaishi.github.io/math-physics/
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
nav:
  - Home: index.md
  - 数学: mathematics/index.md
  - 物理: physics/index.md
  - コンピュータサイエンス: computer/index.md
markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex: { generic: true }  # KaTeX/MathJax
extra_javascript:
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/contrib/auto-render.min.js
extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css